#!/usr/bin/env bash
# Script: 1-install_nginx_web_server
# Description: Configures a new Ubuntu machine to install and configure Nginx web server.
# Requirements:
#   - Installs Nginx on the server
#   - Configures Nginx to listen on port 80
#   - Allows incoming traffic on port 80 through the firewall
#   - Sets the owner of the /var/www directory to the current user
#   - Returns a page with the string "Hello World!" when queried at root / using curl

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure firewall to allow incoming traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Create the "Hello World!" page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations
sudo nginx -t

# Reloading Nginx
sudo service nginx reload
