#!/usr/bin/env bash
# Script: 3-redirection
# Description: Configures a new Ubuntu machine to redirect /redirect_me to another page.
# Requirements:
#   - Configures Nginx to redirect /redirect_me with a "301 Moved Permanently" status code
#   - Sets the redirection target to a specific page

# Install Nginx (if not already installed)
apt-get update > /dev/null 2>&1
apt-get install -y nginx > /dev/null 2>&1


# Create the index.html file with "Hello World!" content if it doesn't exist
echo "Hello World!" | sudo tee /etc/nginx/html/index.html

# Configure the redirection in Nginx
rewrite_rule="rewrite ^/redirect_me(.*) https://github.com/emmy3000 permanent;"
config_file="/etc/nginx/sites-enabled/default"

sudo sed -i "/server_name _;/a \\\t$rewrite_rule" "$config_file"

# Restart Nginx
sudo service nginx restart
