#!/usr/bin/env bash
# Script: 4-not_found_page_404
# Description: Configures a new Ubuntu machine with a custom 404 page in Nginx.
# Requirements:
#   - Configures Nginx to return a 404 error code for non-existing pages
#   - Sets a custom 404 page with the message "Ceci n'est pas une page"

# Install Nginx (if not already installed)
apt-get update > /dev/null
apt-get install -y nginx > /dev/null

# Create the /etc/nginx/html directory
mkdir /etc/nginx/html

# Create the index.html file with "Hello World!" content
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# Create the 404.html file with "Ceci n'est pas une page" content
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure the redirection and custom 404 page in Nginx
printf '%s' "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
