#!/usr/bin/env bash
# Script: 4-not_found_page_404
# Description: Configures a new Ubuntu machine with a custom 404 page in Nginx.
# Requirements:
#   - Configures Nginx to return a 404 error code for non-existing pages
#   - Sets a custom 404 page with the message "Ceci n'est pas une page"

# Install Nginx (if not already installed)
apt-get update > /dev/null
apt-get install -y nginx > /dev/null

# Update Nginx configuration to set the custom error page
error_page_update="listen 80 default_server;
    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }"

sudo sed -i "s|listen 80 default_server;|$error_page_update|" /etc/nginx/sites-enabled/default

# Create the 404.html file with "Ceci n'est pas une page" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Restart Nginx
sudo service nginx restart
