#!/usr/bin/env bash
# Configure Nginx to add a custom HTTP response header (X-Served-By)
sudo apt update
sudo apt install -y nginx
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_response_header.conf
sudo service nginx restart
