#!/usr/bin/env bash
#
# Install and configure HAProxy
#
# This script installs and configures HAProxy on a new Ubuntu machine to meet the specified requirements.
# It distributes traffic using a round-robin algorithm to web-01 and web-02 servers.
# HAProxy can be managed via an init script, and the servers are configured with the correct hostnames.
#
# Requirements:
# - Ubuntu machine with appropriate hostname configuration
#
# Usage: ./1-install_load_balancer
#

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s

defaults
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 221827-web-01:80 check
    server web-02 221827-web-02:80 check
EOT

# Enable and start HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy
