#!/usr/bin/env bash
# Fix for Nginx not listening on port 80 in Ubuntu container
# Script to configure Nginx to listen on port 80

# Remove the default configuration file
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the available configuration file
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart
