#!/usr/bin/env bash
#This init script manages the manage_my_process script by starting, stopping and restarting the process.
#It creates a PID file in /var/run/my_proces.pid when executed with "start", kills the process and deletes
#the PID file with the command "stop", and stops the current process, deletes the PID file, and starts a
#new instance with the command "restart".
#
#USAGE:
#	manage_my_process "{start|stop|restart}"
#
#N.B:script is only meant for process management and & PID file creation/deletion, and doesn't handle cases where
#a process is already running.

pid_file="/var/run/my_process.pid"

if [ "${1}" == "start" ]
then
	./manage_my_process &
	touch "${pid_file}"
	echo "$!" > "${pid_file}"
	echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm "${pid_file}"
	echo "manage_my_process stopped"
elif [ "${1}" == "restart" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm "${pid_file}"
	./manage_my_process &
	touch "${pid_file}"
	echo "$!" > "${pid_file}"
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi

