#!/usr/bin/env bash
#script displays "To infinity and beyond" indefinitely
#with a 2-sceond pause between each iteration.

trap "echo 'I am invincible!!!'" SIGTERM

while true
do
	echo "To inifinity and beyond"
	sleep 2
done

