#!/usr/bin/env bash
#script displays content of the filr /etc/passwd
#following to be displayed are;
#username
#user id
#home directory path for user

if [ ! -f "/etc/passwd" ]; then
	echo "File /etc/passwd does not exist!"
	exit 1
fi

while read -r line; do
	if [ -z "$line" ]; then
		continue
	fi
	echo "$line" | cut -d ':' -f 1,3,6
done < "/etc/passwd"

