#!/usr/bin/env bash
#script displays contents of the file /etc/passwd,
#and does its iteration with a while loop and
# the special variable IFS (Internal Field Seperator)

while IFS=':' read -r user pass uid gid desc home shell; do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $desc"
done < /etc/passwd

