#!/usr/bin/env bash
#Bash script parses an Apache log file and prints the visitor IP with the HTTP
#status code, and groups visitors by IP and HTTP status code, displaying the data in
#descending order of occurence number. The script uses awk and avoids used while, for,
#until, and cut.

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | sort -rn

