#!/usr/bin/env bash
#This script displays numbers from 1 to 20 and shows specific messages 
#for the 4th, 9th and 17th iteration.

counter=1

while [ $counter -le 20 ]

do
	case $counter in
	4)	
		echo "4 bad luck from China"
		;;
	9)	
		echo "9 bad luck from Japan"
		;;
	17)	
		echo "17 bad luck from Italy"
		;;
	*)	
		echo	$counter
		;;
	esac

	counter=$((counter+1))
done
