#!/usr/bin/env bash
#This script displays the time for 12 hours and 59 minutes
#by looping through the hours from 0 to 12 
#and minutes from 1 to 59 using a while loop. 

hour=0

while [ $hour -lt 13 ]

do
	echo "Hour: $hour"
	minute=1

	while [ $minute -lt 60 ]
	do
		echo "$minute"
		minute=$((minute+1))
	done

	hour=$((hour+1))
done

