#!/usr/bin/env bash
#Script writes to output a files's metadata with emphasis
#on its existence and status in a current directory.
#It utilizes if-else statements alone for checking
#both conditions.

FILE="./school"

if [ -e "$FILE" ]; then
	echo "school file exists"

	if [ -s "$FILE" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "$FILE" ]; then
		echo "school is regular file"
	fi

else
	echo "school file does not exist"
fi

