#!/usr/bin/env bash
#########################
#
#script configures an Ubuntu server to resolve localhost to 127.0.0.2 and
#facebook.com to 8.8.8.8
#
##########################

cp /etc/hosts ~/hosts.txt
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.txt
sudo cp -f ~/hosts.txt /etc/hosts
