#!/usr/bin/env bash
#########################
#
#script configures an Ubuntu server to resolve localhost to 127.0.0.2 and
#facebook.com to 8.8.8.8
#
##########################

#if [[ $EUID -ne 0 ]]; then
#	echo "This cript must be run as root." >&2
#fi

#sudo sed -i '/localhost/s/$/ 127.0.0.2/' /etc/hosts
#sudo sed -i '/facebook.com/s/$/ 8.8.8.8/' /etc/hosts

#echo "Localhost now resolves to 127.0.0.2"; echo "facebook.com now resolves to 8.8.8.8"

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
