#!/usr/bin/env bash
# Run the Docker container with port mapping
docker run -p 8080:80 -d -it holbertonschool/265-0

# Connect to the running Docker container
docker exec -it $(docker ps -qf "ancestor=holbertonschool/265-0") /bin/bash -c '
    # Edit the default Apache configuration file to update the content served at the root
    sed -i "s/Hello World/Hello Holberton/" /var/www/html/index.html

    # Restart the Apache service
    service apache2 restart
'
