#!/usr/bin/env bash
# Script runs the whoami command under a specified user
# Usage: ./whoami_script.sh <username>

if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

su -c "whoami" -s /bin/bash $1
